# Site Info
title: Jinho Ko
image: /public/profile.jpeg
tagline: 'Tech Blog'
baseurl: "/literally-everything"
url: http://dgggit.github.io/literally-everything
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: '<!-- more -->'
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Jinho Ko
  description: <strong>Jinho Ko</strong>'s Tech Blog

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  Contents:
    - '/contents/'
    - { c1: '/contents/c1/'}
    - { c2: '/contents/c2/'}
    - { c3: '/contents/c3/'}
    - { c4: '/contents/c4/'}
    - { c5: '/contents/c5/'}
    - { c6: '/contents/c6/'}
    - { c7: '/contents/c7/'}
  About:          
    - '/about/'
  Homepage: 
    - 'http://dgggit.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

mainpage:
  image: /public/img/quote-long.jpg
  caption: from the movie <strong>Midnight in Paris (2011)</strong>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-156068228-2' # tracking ID for my techblog
disqus_short_name: 'jinhoko' 

