# Site Info
title: Jinho Ko
image: /public/profile.jpeg
tagline: 'Tech Blog'
baseurl: "/literally-everything"
othersurl: 'literally-everything/others/'
url: http://dgggit.github.io/literally-everything
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: '<!-- more -->'
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/contents/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Jinho Ko
  description: <strong>Jinho Ko</strong>'s Tech Blog

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
#  Blog:           
#    - '/blog/'
#    - { Categories: '/blog/categories/' }
#    - { Tags: '/blog/tags/' }
  Contents:
    - '/contents/'
    - { Statistics: '/contents/statistics/'}
    - { Computational Stats.: '/contents/compstats/'}
    - { Bayesian + ML: '/contents/bayesianML/'}
    - { Deep Learning + AI: '/contents/DL/'}
    - { NLP: '/contents/NLP'}
    - { Big Data Mining: '/contents/bigdatamining/'}
    - { System Programming: '/contents/systemprog/'}
    - { Python Dev: '/contents/pythondev/'}
    - { Linear Algebra: '/contents/linalgebra/'}
    - { Numerical Analysis: '/contents/numanalysis/'}
    - { Etc: '/contents/etc/'}
  Others:
    - '/others/'
    - { Paper Review: '/others/paperreview/'}
    - { Great Sites: '/others/greatsites/'}
    - { Personal Interests: '/others/personalinterests/'}
  Tags: 
    - '/contents/tags/' 
  About:          
    - '/about/'


# link to post
collections:
  posts:
    output: true
    permalink: /:collection/:name

# Where are tags and categories displayed
tag_page: '/contents/tags/'
category_page: '/contents/categories/'

mainpage:
  image: /public/img/quote-long.jpg
  caption: from the movie <strong>Midnight in Paris (2011)</strong>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-156068228-2' # tracking ID for my techblog
disqus_short_name: 'jinhoko' 

