# Site Info
title: Codinfox Lanyon
image: /public/profile.jpeg
tagline: 'Tech Blog'
baseurl: "/literally-everything"
url: http://dgggit.github.io/literally-everything
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Jinho Ko
  description: Jinho Ko's Tech Blog

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Contents:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Personal Homepage: 
    - 'http://dgggit.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

mainpage:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: from the movie <strong>Midnight in Paris(2011)</strong>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-156068228-2' # tracking ID for my techblog
disqus_short_name: 'dg_jhko' 

